name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute 00:00 UTC on the 1th in Mar, Jun, Sep and Dec
    - cron: "0 0 1 3,6,9,12 *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.SUMMARY_CARDS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
